Repository it-moji/it-moji-client, pull requests merged in 2025-04, with the labels that each got.

#11 출석 배지 관련 API 인터페이스 변경사항 반영 외 2건
  src/app/admin/attendance/text-parsing/page.tsx
  src/app/admin/error.tsx
  src/entities/attendance-badge/@x/attendance-option.ts
  src/entities/attendance-badge/api/mocks/badge-list.ts
  src/entities/attendance-badge/api/use-badge-list-with-conditions-query.ts
  src/entities/attendance-badge/config/range.ts
  src/entities/attendance-badge/model/schema.ts
  src/entities/attendance-option/api/use-create-detail-option.ts
  src/entities/attendance-option/api/use-delete-detail-option.ts
  src/entities/attendance-option/api/use-modify-detail-option.ts
  src/entities/attendance-option/model/schema.ts
  src/entities/text-parsing/@x/attendance-option.ts
  src/entities/text-parsing/api/create-parsing-result.ts
  src/entities/text-parsing/api/endpoint.ts
  src/entities/text-parsing/api/get-parsing-options.ts
  src/entities/text-parsing/api/index.ts
  src/entities/text-parsing/api/mocks/parsing-result.ts
  src/entities/text-parsing/api/modify-parsing-options.revalidate.ts
  src/entities/text-parsing/api/modify-parsing-options.ts
  src/entities/text-parsing/api/query-keys.ts
  src/entities/text-parsing/api/use-is-parsing-mutating.ts
  src/entities/text-parsing/api/use-modify-parsing-options.ts
  src/entities/text-parsing/api/use-parsing-options-query.ts
  src/entities/text-parsing/config/til-template.ts
  src/entities/text-parsing/lib/helpers/parse-text.ts
  src/entities/text-parsing/lib/helpers/test/create-test-data.ts
  src/entities/text-parsing/lib/helpers/test/determine-attendance-info.test.ts
  src/entities/text-parsing/lib/helpers/test/extract-name.test.ts
  src/entities/text-parsing/lib/helpers/test/generate-attendance-info.test.ts
  src/entities/text-parsing/lib/helpers/test/get-attendance-badge-id.test.ts
  src/entities/text-parsing/lib/helpers/test/transform-attendance-info-to-statistic.test.ts
  src/entities/text-parsing/lib/helpers/transform-attendance-info-to-statistic.ts
  src/entities/text-parsing/model/schema.ts
  src/entities/text-parsing/model/text-parsing-state.ts
  src/views/attendance-badge/ui/attendance-badge-form-container.tsx
  src/views/attendance-badge/ui/attendance-badge-form.tsx
  src/views/text-parsing/ui/text-parsing-input.tsx
  src/views/text-parsing/ui/text-parsing-options-setting.tsx
  src/views/text-parsing/ui/text-parsing-page.tsx
  src/views/text-parsing/ui/text-parsing-result-form.tsx
  src/views/text-parsing/ui/text-parsing-result-statistic.tsx
  src/views/text-parsing/ui/text-parsing-result.tsx
  src/widgets/attendance-options-select/ui/attendance-option-select.tsx
Labels: 📚 refactor, 🔧 features

#12 텍스트 파싱 관련 오동작 수정 및 배지 아이콘 복사 UI 추가
  src/views/text-parsing/ui/text-parsing-options-setting.tsx
  src/views/text-parsing/ui/text-parsing-result-form.tsx
Labels: 🚨 fix, 🔧 features

#14 텍스트 파싱 결과 폼 사용성 개선을 위한 인풋/폼 초기화, 텍스트 파싱 예외 처리 기능 추가
  src/entities/text-parsing/lib/helpers/parse-text.ts
  src/entities/text-parsing/model/index.ts
  src/entities/text-parsing/model/schema.ts
  src/entities/text-parsing/model/text-parsing-exception.ts
  src/entities/text-parsing/model/text-parsing-state.ts
  src/views/text-parsing/lib/helpers/parse-text-safely.ts
  src/views/text-parsing/ui/text-parsing-input.tsx
  src/views/text-parsing/ui/text-parsing-result-error-fallback.stories.tsx
  src/views/text-parsing/ui/text-parsing-result-fallback-ui.tsx
  src/views/text-parsing/ui/text-parsing-result-form-fields.tsx
  src/views/text-parsing/ui/text-parsing-result-form.tsx
  src/views/text-parsing/ui/text-parsing-result-statistic.tsx
  src/views/text-parsing/ui/text-parsing-result.tsx
Labels: 🔧 features
